import Link from 'next/link'
import Image from 'next/image'
import { ArrowLeft, Clock, CreditCard, MapPin, Package, User } from 'lucide-react'
import { transitionOrderAction } from '@/actions/crm'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { type RailsCrmOrderDetail, type RailsCrmOrderItem } from '@/lib/rails-admin'

const orderStatuses = ['payment_pending', 'paid', 'shipped', 'delivered', 'refund_pending', 'cancelled']
const statusLabels: Record<string, string> = {
  payment_pending: 'Ожидает оплаты', paid: 'Оплачен', shipped: 'Отправлен', delivered: 'Доставлен', refund_pending: 'Возврат', cancelled: 'Отменен',
}

export default function CrmOrderDetail({ order }: { order: RailsCrmOrderDetail; replacementSearch?: string; replacementItem?: string; replacementProducts?: unknown[] }) {
  return (
    <main className="min-h-full bg-slate-950 px-4 py-8 text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div><Link href="/admin/crm/orders" className="inline-flex items-center gap-2 text-sm font-medium text-sky-300 hover:text-sky-200"><ArrowLeft className="h-4 w-4" />Заказы</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-white">{order.public_number}</h1><Badge className="bg-sky-500/15 text-sky-200 hover:bg-sky-500/15">{statusLabel(order.status)}</Badge></div><p className="mt-2 text-sm text-slate-500">Заказ создан {formatDate(order.created_at)}</p></div>
          <Card className="w-full border-slate-800 bg-slate-900 text-slate-100 lg:w-[380px]"><CardHeader><CardTitle className="text-base">Изменить статус</CardTitle><CardDescription className="text-slate-500">Статус оплаты обновляется автоматически после колбэка Platega.</CardDescription></CardHeader><CardContent><form action={transitionOrderAction} className="space-y-3"><input type="hidden" name="orderId" value={String(order.id)} /><select name="toStatus" defaultValue={order.status} className="w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white">{orderStatuses.map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select><textarea name="message" placeholder="Комментарий" className="min-h-16 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" /><Button type="submit" className="w-full bg-sky-600 hover:bg-sky-500">Сохранить</Button></form></CardContent></Card>
        </div>

        <section className="grid gap-4 md:grid-cols-3"><Metric icon={CreditCard} label="Итого" value={formatMoney(order.total_cents, order.currency)} /><Metric icon={Package} label="Товаров" value={String(order.items?.length || 0)} /><Metric icon={Clock} label="Оплата" value={order.paid_at ? formatDate(order.paid_at) : 'Не оплачено'} /></section>
        <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
          <div className="space-y-4"><Card className="border-slate-800 bg-slate-900 text-slate-100"><CardHeader><CardTitle className="text-base">Состав заказа</CardTitle></CardHeader><CardContent className="space-y-3">{(order.items || []).map((item) => <OrderItemCard key={item.id} item={item} currency={order.currency} />)}{!order.items?.length && <p className="text-sm text-slate-500">Товары не найдены</p>}</CardContent></Card><TimelineCard order={order} /></div>
          <aside className="space-y-4"><CustomerCard order={order} /><CheckoutCard order={order} /><PaymentsCard order={order} /></aside>
        </section>
      </div>
    </main>
  )
}

function OrderItemCard({ item, currency }: { item: RailsCrmOrderItem; currency?: string }) {
  return <div className="flex gap-4 rounded-md border border-slate-800 bg-slate-950/50 p-4"><div className="h-24 w-20 shrink-0 overflow-hidden rounded bg-slate-800">{item.image_url ? <Image src={item.image_url} alt="" width={80} height={96} unoptimized className="h-full w-full object-cover" /> : <div className="h-full w-full bg-slate-800" />}</div><div className="min-w-0 flex-1"><div className="font-medium text-white">{item.title}</div>{item.product_url && <a href={item.product_url} target="_blank" rel="noreferrer" className="mt-1 block truncate text-sm text-sky-300 hover:text-sky-200">Открыть товар</a>}<div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-400"><span>Количество: {item.quantity}</span>{item.size && <span>Размер: {item.size}</span>}<span>Сумма: {formatMoney(item.total_price_cents, currency)}</span></div></div></div>
}

function CustomerCard({ order }: { order: RailsCrmOrderDetail }) { const customer = order.customer; return <Card className="border-slate-800 bg-slate-900 text-slate-100"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><User className="h-4 w-4 text-sky-300" />Клиент</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-400"><Info label="Имя" value={customer?.display_name} /><Info label="Электронная почта" value={customer?.email} /><Info label="Телефон" value={customer?.phone} /><Info label="Telegram" value={customer?.telegram_username ? `@${customer.telegram_username}` : undefined} /><Info label="Источник" value={sourceLabel(customer?.registration_source)} />{order.customer_comment && <Info label="Комментарий" value={order.customer_comment} />}</CardContent></Card> }
function CheckoutCard({ order }: { order: RailsCrmOrderDetail }) { const checkout = order.checkout; if (!checkout) return null; return <Card className="border-slate-800 bg-slate-900 text-slate-100"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-4 w-4 text-sky-300" />Доставка</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-400"><Info label="Получатель" value={checkout.full_name} /><Info label="Телефон" value={checkout.phone} /><Info label="Город" value={checkout.city} /><Info label="Адрес" value={checkout.address_line} /><Info label="Индекс" value={checkout.postal_code} /><Info label="Комментарий" value={checkout.delivery_comment} /></CardContent></Card> }
function PaymentsCard({ order }: { order: RailsCrmOrderDetail }) { return <Card className="border-slate-800 bg-slate-900 text-slate-100"><CardHeader><CardTitle className="text-base">Платежи и возвраты</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{(order.payments || []).map((payment) => <div key={payment.id} className="flex items-center justify-between gap-3 rounded-md border border-slate-800 bg-slate-950 p-3"><span className="text-slate-300">{paymentLabel(payment.status)}</span><span className="text-slate-300">{formatMoney(payment.amount_cents, payment.currency)}</span></div>)}{(order.refunds || []).map((refund) => <div key={refund.id} className="flex items-center justify-between gap-3 rounded-md border border-slate-800 bg-slate-950 p-3"><span className="text-slate-300">Возврат · {refundStatusLabel(refund.status)}</span><span className="text-slate-300">{formatMoney(refund.amount_cents, refund.currency)}</span></div>)}{!order.payments?.length && !order.refunds?.length && <span className="text-slate-500">Платежей нет</span>}</CardContent></Card> }
function TimelineCard({ order }: { order: RailsCrmOrderDetail }) { return <Card className="border-slate-800 bg-slate-900 text-slate-100"><CardHeader><CardTitle className="text-base">История статусов</CardTitle></CardHeader><CardContent className="space-y-3">{(order.timeline || []).slice().reverse().map((event) => <div key={event.id} className="border-l border-slate-700 pl-3"><div className="text-sm font-medium text-slate-200">{statusLabel(event.to_status || event.from_status || '')}</div><div className="mt-1 text-xs text-slate-500">{formatDate(event.created_at)}</div>{event.message && <div className="mt-1 text-sm text-slate-400">{event.message}</div>}</div>)}{!order.timeline?.length && <div className="text-sm text-slate-500">История пуста</div>}</CardContent></Card> }
function Metric({ icon: Icon, label, value }: { icon: any; label: string; value: string }) { return <div className="rounded-lg border border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-slate-500"><Icon className="h-4 w-4 text-sky-300" />{label}</div><div className="mt-3 text-lg font-semibold text-white">{value}</div></div> }
function Info({ label, value }: { label: string; value?: string | null }) { return <div className="flex justify-between gap-3"><span className="text-slate-500">{label}</span><span className="max-w-[65%] text-right text-slate-200">{value || '—'}</span></div> }
function statusLabel(status?: string) { return statusLabels[status || ''] || 'Неизвестно' }
function sourceLabel(source?: string | null) { return source === 'telegram_mini_app' ? 'Telegram Mini App' : 'Сайт' }
function paymentLabel(status?: string) { return ({ succeeded: 'Оплачен', pending: 'Ожидает оплаты', failed: 'Ошибка оплаты', refunded: 'Возвращен' } as Record<string, string>)[status || ''] || status || 'Неизвестно' }
function refundStatusLabel(status?: string) { return ({ requested: 'Запрошен', approved: 'Подтвержден', processing: 'Обрабатывается', paid: 'Возвращен', failed: 'Ошибка', rejected: 'Отклонен' } as Record<string, string>)[status || ''] || 'Неизвестно' }
function formatMoney(value?: number | null, currency = 'RUB') { return typeof value === 'number' ? new Intl.NumberFormat('ru-RU', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value / 100) : '—' }
function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '—' }
